language: java
jdk:
- oraclejdk9
branches:
  only:
  - master
env:
  global:
  - secure: KaQFjEJ4+T908NWsbn6YagoaHerFKUtnz6I3oqSHKx3te6b3/Yw+7m82yJDrfvPpdX/HyKMJbHo2ciYFwKVKYeTrPx5fGdPZhFJFy5Mbv3XqL9eC7TAtnSn+gpm4Jd957nAE2Q7GSIQGtwrDsGnut+Nl06H+zMkOgvyoz6kGJKfeY4V4zNjmxL2690BH4kRgam6Y8DnAvFModLun/6enPUuy7ypSsc2McUYjbVtvHRXAHv64uRX6zb7FxWobSLK0q8Hr16lqJr3XI70XYIC0qN2zJmNuVmmRvPAkca2C1VS4FntNJzs8Ju+5araIwzM2CRzlIbIaOlAJjjbfHVIcIRYg3/KQUIOpzbIA8tF2sU6TUFgLmSjPGx9B9p/FFBAs5wDNM22hXYRqAxSQxTMF+zNSytJZQQ0utSqdoPOl9MyGXMKVsWgjff7bNocf9Mc41bHo9HL4XpiaSsJdcMRmhlHrS9Av+yrrOpcY+QJfnoyDP8YBtPINvCRJ5ZF54DHsDjbp4tQBXKhy2fOxis454BgXKVyFfDY37brn/a2tEbcSdYBydqINEDIKdaZ3dnr83UUhKeP36kvwPR09LkajolsOnukuA1M/p7MmTAlBB9Nqpr9DHB40dQWSoEUZ/ba86fuhSLiQdkjNCwgKIkUXrAVc72buzs9zcFZIdbPNKzk=
  - secure: gd0oZHKK50MJUEpHkxP9JwA7OJkml2vH3hnkhiQHN9P4pcTFskGdnIrymBT10gelfJL3qwvurbce0DP1l9erJQJ8Cf3Ggbc0UwgJqEYQrcoSHpWOryj/LSdqaCUgwW7osFWPD5K9Wm2bPcpQtbxJcv1hgSS0HZ6kR4ayeYsDmRKFZRTpDdzRtzXuYLtlCH0P4l6KPP3zjsSVuLQc+hGKQ5YIV6ABgpDjpFdLyk/JgrJo4RVx+s+AsOYtVmDMXo7ecFK3fe7C5W80zFv3ZNuWmm60BHTgGKBRuJ7+h8Tn5ivuKu/JGGauvnaPxje1c7HAL3TTNRh0CyBHv935o2+zmf4WkXxr6EaCThSy/JHLDJkh5qJxP6Hsds+dUj+o4K+85Wk/XKtpC4wklGpym4YdXkSGvwvSh9OXY16qXlNMVMJ0fRhOJylB+6YhaEYKmkM+rFHKCtLgiW/bkSOzuPlQ9AL8gLdxcdmkEFCBBX5uHeI8XspGHjmn9F85qQpVGHCDSCLrR255C8C4XajKXl7PRRcA9GEJsFs6MsWTM/dZ2pNi2eAQ4qz/HHjnQiiyD5y5DfzoYuUWbWRbS2z+4gqOaHQOhVXOxfLmrTQVJxF2GLeIHJJVJisxwbPQrxyUDHAt7UGrnAzSiBYrWJ0JZV2bmf80nc22QaJiL9JAjGJo08U=
install: true
script: ./travis.sh
